# 線形代数

## 行列

以下のように縦横に数を並べたものを **行列** と呼ぶ

$$
\boldsymbol{X} = \left(\begin{array}{cc} 1 & 2 \\ 3 & 4 \\ 5 & 6 \end{array}\right)
$$

行列の横の並びを **行**、縦の並びを **列** と呼び、$m\times{n}$ 次元の行列は以下のように定義される

$$
\boldsymbol{A} = \left(
\begin{array}{cccc}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{array}
\right)
$$

行列の $i$ 行目、$j$ 行目にあたる成分を $(i, j)$ 成分と呼び、特に混乱がない場合は $a_{21}$ は $(2, 1)$ 成分を意味するものとする

### 行列の演算
行列の和、差、スカラー倍などは、ベクトルのときと同様に、各成分ごとの演算により定義される

$$
\begin{align}
\boldsymbol{A} + \boldsymbol{B} &= \left(
\begin{array}{cccc}
a_{11} + b_{11} & a_{12} + b_{12} & \ldots & a_{1n} + b_{1n} \\
a_{21} + b_{21} & a_{22} + b_{22} & \ldots & a_{2n} + b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} + b_{m1} & a_{m2} + b_{m2} & \ldots & a_{mn} + b_{mn}
\end{array}
\right) \\
k\boldsymbol{A} &= \left(
\begin{array}{cccc}
ka_{11} & ka_{12} & \ldots & ka_{1n} \\
ka_{21} & ka_{22} & \ldots & ka_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
ka_{m1} & ka_{m2} & \ldots & ka_{mn}
\end{array}
\right) \\
-\boldsymbol{A} &= \left(
\begin{array}{cccc}
-a_{11} & -a_{12} & \ldots & -a_{1n} \\
-a_{21} & -a_{22} & \ldots & -a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
-a_{m1} & -a_{m2} & \ldots & -a_{mn}
\end{array}
\right) \\
\boldsymbol{A} - \boldsymbol{B} &= \boldsymbol{A} + (-\boldsymbol{B}) = \left(
\begin{array}{cccc}
a_{11} - b_{11} & a_{12} - b_{12} & \ldots & a_{1n} - b_{1n} \\
a_{21} - b_{21} & a_{22} - b_{22} & \ldots & a_{2n} - b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} - b_{m1} & a_{m2} - b_{m2} & \ldots & a_{mn} - b_{mn}
\end{array}
\right)
\end{align}
$$

上記の通り、行列の和・差が定義されるのは、2つの行列のサイズ（次元数）が一致する場合のみである

次に、行列とベクトルの積を定義する

$$
\boldsymbol{A} = \left(
\begin{array}{cccc}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{array}
\right), \quad \vec{v} = \left(\begin{array}{c} v_1 \\ v_2 \\ v_n \end{array}\right) \\
\boldsymbol{A}\vec{v} = \left(
\begin{array}{cccc}
a_{11}v_{1} & a_{12}v_{2} & \ldots & a_{1n}v_{n} \\
a_{21}v_{1} & a_{22}v_{2} & \ldots & a_{2n}v_{n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1}v_{1} & a_{m2}v_{2} & \ldots & a_{mn}v_{n}
\end{array}
\right)
$$

これはつまり、$\boldsymbol{A}$ の各行をベクトルとみなし、それらのベクトルと $\vec{v}$ の内積を並べたものとなる

上記定義から分かるように、積が定義されるのは行列の行数とベクトルの次元が一致する場合のみである

行列の積の応用として典型的なのは、連立方程式の表記の簡略化である

例えば、次のような連立方程式を考える

$$
\left\{
\begin{align}
& 2x + y + 3z = 7 \\
& x -y + z = 4 \\
& x + 2y - z = -3
\end{align}
\right.
$$

これは、行列を使って以下のように書くことが出来る

$$
\left(
\begin{array}{ccc}
2 & 1 & 3 \\
1 & -1 & 1 \\
1 & 2 & -1
\end{array}
\right) \left(\begin{array}{c} x \\ y \\ z \end{array}\right)
=
\left(\begin{array}{c} 7 \\ 4 \\ -3 \end{array}\right)
$$

同様に行列同士の積も定義できる

行列積 $\boldsymbol{A}\boldsymbol{B}$ が定義できるのは、$\boldsymbol{A}$ の列数と $\boldsymbol{B}$ の行数が等しい場合のみで、以下のように定義される

$$
\boldsymbol{A}\boldsymbol{B} = \left(\begin{array}{cccc} \boldsymbol{A}b_1 & \boldsymbol{A}b_2 & \ldots & \boldsymbol{A}b_l \end{array}\right)
=
\left(
\begin{array}{cccc}
\sum_{k=1}^{n}a_{1k}b_{k1} & \sum_{k=1}^{n}a_{1k}b_{k2} & \ldots & \sum_{k=1}^{n}a_{1k}b_{kl} \\
\sum_{k=1}^{n}a_{2k}b_{k1} & \sum_{k=1}^{n}a_{2k}b_{k2} & \ldots & \sum_{k=1}^{n}a_{2k}b_{kl} \\
\vdots & \vdots & \ddots & \vdots \\
\sum_{k=1}^{n}a_{mk}b_{k1} & \sum_{k=1}^{n}a_{mk}b_{k2} & \ldots & \sum_{k=1}^{n}a_{mk}b_{kl}
\end{array}
\right)
$$

ここで、行列の積については交換法則 $\boldsymbol{A}\boldsymbol{B} = \boldsymbol{B}\boldsymbol{A}$ が成り立たないことに注意

一般には計算結果が一致しないだけでなく $\boldsymbol{A}\boldsymbol{B}$ が定義されているのに $\boldsymbol{B}\boldsymbol{A}$ が定義されないことすらありえる（$\boldsymbol{B}$ の列数と $\boldsymbol{A}$ の行数が一致しない場合）

行列の積については、以下の法則が知られている

$$
\begin{align}
(k\boldsymbol{A})\boldsymbol{B} &= k(\boldsymbol{A}\boldsymbol{B}) \\
(\boldsymbol{A}\boldsymbol{B})\boldsymbol{C} &= \boldsymbol{A}(\boldsymbol{B}\boldsymbol{C}) \quad （結合法則） \\
\boldsymbol{A}(\boldsymbol{B} + \boldsymbol{C}) &= \boldsymbol{A}\boldsymbol{B} + \boldsymbol{A}\boldsymbol{C} \\
(\boldsymbol{A} + \boldsymbol{B})\boldsymbol{C} &= \boldsymbol{A}\boldsymbol{C} + \boldsymbol{B}\boldsymbol{C} \quad （分配法則）
\end{align}
$$

全成分が 0 であるような行列を **ゼロ行列** と呼び、サイズ $m\times{n}$ であるようなゼロ行列は $\boldsymbol{0}_{m,n}$ と表記する

$\boldsymbol{A}$ が $m\times{n}$ 行列であるならば、次の法則が成り立つ

$$
\begin{align}
\boldsymbol{A} + \boldsymbol{0}_{m,n} &= \boldsymbol{0}_{m,n} + \boldsymbol{A} = \boldsymbol{A} \\
\boldsymbol{A}\boldsymbol{0}_{n,l} &= \boldsymbol{0}_{m,l} \\
\boldsymbol{0}_{l,m}\boldsymbol{A} &= \boldsymbol{0}_{l,n}
\end{align}
$$

### 転置
行列 $\boldsymbol{A}$ の **転置** とは、$\boldsymbol{A}$ の行と列を入れ替えたもので $\boldsymbol{A}^T$ と記述する

すなわち $m\times{n}$ 行列である $\boldsymbol{A}$ の転置行列は以下のように定義される

$$
\boldsymbol{A}^T = \left(
\begin{array}{cccc}
a_{11} & a_{21} & \ldots & a_{m1} \\
a_{12} & a_{22} & \ldots & a_{m2} \\
\vdots & \vdots & \ddots & \vdots \\
a_{1n} & a_{2n} & \ldots & a_{mn}
\end{array}
\right)
$$

行列の転置については、次の式が成り立つ

$$
\begin{align}
(\boldsymbol{A}^T)^T &= \boldsymbol{A} \\
(\boldsymbol{A}\boldsymbol{B})^T &= \boldsymbol{B}^T\boldsymbol{A}^T
\end{align}
$$

#### 演習1
行列 $\boldsymbol{A}, \boldsymbol{B}, \boldsymbol{C}, \boldsymbol{D}$ が次の通り与えられている時、

$$
\boldsymbol{A}=\begin{pmatrix}2&1\\-1&1\end{pmatrix},\ 
\boldsymbol{B}=\begin{pmatrix}1&-1\\1&1\end{pmatrix},\ 
\boldsymbol{C}=\begin{pmatrix}1&2\\2&1\\-1&2\end{pmatrix},\ 
\boldsymbol{D}=\begin{pmatrix}1&-1&0\\0&1&2\\0&0&1\end{pmatrix}
$$

以下を求めよ

1. $2\boldsymbol{A}$
2. $\boldsymbol{A}+\boldsymbol{B}$
3. $\boldsymbol{A}-\boldsymbol{B}$
4. $2\boldsymbol{A}-3\boldsymbol{B}$
5. $\boldsymbol{A}\boldsymbol{B}$
6. $\boldsymbol{B}\boldsymbol{C}^T$
7. $\boldsymbol{C}^T\boldsymbol{D}$

#### 演習2
行列 $\boldsymbol{X}$ が $1000\times{100}$ 行列、$\boldsymbol{Y}$ が $100\times{500}$ 行列、$\boldsymbol{Z}$ が $1000\times{500}$ 行列のとき、次の行列のサイズを求めよ

1. $\boldsymbol{X}\boldsymbol{Y}$
2. $(\boldsymbol{X}\boldsymbol{Y}\boldsymbol{Z}^T\boldsymbol{X})^T\boldsymbol{X}$

#### 演習3
行列 $\boldsymbol{A}, \boldsymbol{B}, \boldsymbol{C}$ について、次の式が成り立つことを証明せよ

$$
(\boldsymbol{A}\boldsymbol{B}^T\boldsymbol{C})^T = \boldsymbol{C}^T\boldsymbol{B}\boldsymbol{A}^T
$$

#### 解1
![01_practice03a_1.drawio.png](./img/01_practice03a_1.drawio.png)

#### 解2
![01_practice03a_2.drawio.png](./img/01_practice03a_2.drawio.png)

#### 解3
![01_practice03a_3.drawio.png](./img/01_practice03a_3.drawio.png)

In [1]:
# 行列 A, B, C, D
A = [2 1; -1 1]; display(A)
B = [1 -1; 1 1]; display(B)
C = [1 2; 2 1; -1 2]; display(C)
D = [1 -1 0; 0 1 2; 0 0 1]; display(D)

2×2 Matrix{Int64}:
  2  1
 -1  1

2×2 Matrix{Int64}:
 1  -1
 1   1

3×2 Matrix{Int64}:
  1  2
  2  1
 -1  2

3×3 Matrix{Int64}:
 1  -1  0
 0   1  2
 0   0  1

In [2]:
# 2A => [4 2; -2 2]
display(2A)

# A + B => [3 0; 0 2]
display(A + B)

# A - B => [1 2; -2 0]
display(A - B)

# 2A - 3B => [1 5; -5 -1]
display(2A - 3B)

# AB => [3 -1; 0 2]
display(A * B)

# B * C^T => [1 -1; 1 1] * [1 2 -1; 2 1 2] = [-1 1 -3; 3 3 1]
display(B * C')

# C^T * D => [1 2 -1; 2 1 2] * [1 -1 0; 0 1 2; 0 0 1] = [1 1 3; 2 -1 4]
display(C' * D)

2×2 Matrix{Int64}:
  4  2
 -2  2

2×2 Matrix{Int64}:
 3  0
 0  2

2×2 Matrix{Int64}:
  1  2
 -2  0

2×2 Matrix{Int64}:
  1   5
 -5  -1

2×2 Matrix{Int64}:
 3  -1
 0   2

2×3 Matrix{Int64}:
 -1  1  -3
  3  3   1

2×3 Matrix{Int64}:
 1   1  3
 2  -1  4

In [3]:
# X: 1000x100 行列
X = rand(1000, 100)

# Y: 100x500 行列
Y = rand(100, 500)

# Z: 1000x500 行列
Z = rand(1000, 500)

# XY => 1000x500 行列
println("XY: $(size(X*Y)) 行列")

# (X * Y * Z^T * X)^T * X
# => ((1000x500)(500x1000)(1000x100))^T (1000x100)
# => (100x1000)(1000x100)
# => 100x100 行列
println("(X * Y * Z^T * X)^T * X: $(size((X * Y * Z' * X)' * X)) 行列")

XY: (1000, 500) 行列
(X * Y * Z^T * X)^T * X: (100, 100) 行列


### 逆行列と連立方程式
- **正方行列**:
    - 行数と列数が等しい行列のこと
    - サイズ $n\times{n}$ の正方行列を特に $n$ 次正方行列と呼ぶ（$n$: 正方行列の次数）
- **対角行列**:
    - **対角成分**（行列の $(i,i)$ 成分）以外がすべて 0 である正方行列
    - 対角成分が左上から $d_1, \ldots, d_n$ であるような対角行列を ${\rm{diag}}(d_1, \ldots, d_n)$ と表記する

$$
{\rm{diag}}(d_1, \ldots, d_n) = \begin{pmatrix} d_1 & & & \\ & d_2 & & \\ & & \ddots & \\ & & & d_n \end{pmatrix}
$$

一般に行列の積では交換法則が成り立たないが、対角行列同士の積の場合は交換法則が成り立つ

$$
\boldsymbol{D}\boldsymbol{E} = \begin{pmatrix} d_1e_1 &&& \\ & d_2e_2 && \\ && \ddots & \\ &&& d_ne_n \end{pmatrix} = \boldsymbol{E}\boldsymbol{D}
$$

対角成分がすべて 1 である対角行列を特に **単位行列** と呼び、サイズ $n\times{n}$ の単位行列を $\boldsymbol{I}_n$ で表す

$m\times{n}$ 行列 $\boldsymbol{A}$ について、単位行列は次の性質を満たす

$$
\boldsymbol{A}\boldsymbol{I}_n = \boldsymbol{I}_m\boldsymbol{A} = \boldsymbol{A}
$$

正方行列 $\boldsymbol{A}$ に対して、もし $\boldsymbol{A}\boldsymbol{X} = \boldsymbol{I}$ となる $\boldsymbol{X}$ が存在する場合、それを **逆行列** と呼び、$\boldsymbol{A}^{-1}$ で表す

$\boldsymbol{A}\boldsymbol{X} = \boldsymbol{I}$ であれば $\boldsymbol{X}\boldsymbol{A} = \boldsymbol{I}$ も成り立つため、逆行列は以下の性質を満たす

$$
\boldsymbol{A}\boldsymbol{A}^{-1} = \boldsymbol{A}^{-1}\boldsymbol{A} = \boldsymbol{I}
$$

ただし、すべての正方行列に対して逆行列が存在するとは限らないため注意が必要である

逆行列が存在する正方行列を特に **正則行列** と呼び、存在しない正方行列を **非正則行列** と呼ぶ

ここで、行列と連立方程式の関係について、以下の連立方程式を例に考えてみる

$$
\left\{
\begin{align}
& 2x + y = 3 \\
& x - 3y = 5
\end{align}
\right.
$$

これを行列で置換すると、以下のように表すことが出来る

$$
\begin{align}
& \boldsymbol{A} = \begin{pmatrix} 2 & 1 \\ 1 & -3 \end{pmatrix},\ 
\boldsymbol{x} = \begin{pmatrix} x \\ y \end{pmatrix},\ 
\boldsymbol{b} = \begin{pmatrix} 3 \\ 5 \end{pmatrix} \\
& 連立方程式:\ \boldsymbol{A}\boldsymbol{x} = \boldsymbol{b}
\end{align}
$$

もし $\boldsymbol{A}$ が正則行列であるならば、この式の両辺の左から $\boldsymbol{A}^{-1}$ を掛けることで、未知ベクトル $\boldsymbol{x}$ を求めることが出来る

$$
\boldsymbol{A}^{-1}(\boldsymbol{A}\boldsymbol{x}) = (\boldsymbol{A}^{-1}\boldsymbol{A})\boldsymbol{x} = \boldsymbol{I}\boldsymbol{x} = \boldsymbol{x} \\
\\
\begin{align}
& \boldsymbol{A}\boldsymbol{x} = \boldsymbol{b} \ より、\qquad
\boldsymbol{x} = \boldsymbol{A}^{-1}\boldsymbol{b}
\end{align}
$$

$2\times{2}$ 行列 $\boldsymbol{X} = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$ が逆行列を持つための条件は $ad - bc \neq 0$ で、その時の逆行列は以下の式で表される

$$
\boldsymbol{X}^{-1} = \frac{1}{ad - bc}\begin{pmatrix}d & -b \\ -c & a\end{pmatrix}
$$

したがって、この連立方程式は逆行列を計算して以下のように解くことが出来る

$$
\boldsymbol{A}^{-1} = \frac{1}{2\times(-3) - 1\times{1}}\begin{pmatrix}-3 & -1 \\ -1 & 2\end{pmatrix} = -\frac{1}{7}\begin{pmatrix}-3 & -1 \\ -1 & 2\end{pmatrix} \\
\begin{align}
\\
\boldsymbol{x} = \boldsymbol{A}^{-1}\boldsymbol{b} &= -\frac{1}{7}\begin{pmatrix}-3 & -1 \\ -1 & 2\end{pmatrix} \times \begin{pmatrix}3 \\ 5\end{pmatrix} \\
&= -\frac{1}{7}\begin{pmatrix}(-3)\times{3} + (-1)\times{5} \\ (-1)\times{3} + 2\times{5}\end{pmatrix} \\
&= \begin{pmatrix}2\\-1\end{pmatrix}
\end{align}
$$

以上より、解は $x=2,\ y=1$ となる

### 行列式
2次正方行列 $\begin{pmatrix}a&b \\ c&d\end{pmatrix}$ が逆行列を持たない条件は、$ad - bc = 0$ のときだった

$ad - bc = 0$ は $a:b = c:d$ のときに成り立つが、これは $\begin{pmatrix}a \\ b\end{pmatrix}$ と $\begin{pmatrix}c \\ d\end{pmatrix}$ が平行という条件に等しい

つまり2次正方行列は、1行目と2行目のベクトルが平行の時に逆行列を持たないということである

ここで $ad - bc$ のことを **行列式** と呼び、$\det{\boldsymbol{A}}$ と表記する

行列式は、次数2の場合に限らず一般の正方行列で定義可能だが、本稿では触れないものとする

連立方程式が解を持つかどうかは、行列式が 0 にならないかどうかで判断できる

行列式が 0 になってしまう場合は、連立方程式の係数の正方行列が逆行列を持たない、という条件に等しいため、その方程式は解くことができない

ただし、方程式を解くことができないケースはさらに「解を持たない場合」と「解が無限に存在する場合」に分けられる

解を持たない場合の方程式は、具体的には以下のようなものである

$$
\left\{
\begin{align}
& x + 2y = 3 \\
& 2x + 4y = 4
\end{align}
\right.
$$

$$
\begin{align}
&行列:\ \begin{pmatrix}1&2\\2&4\end{pmatrix}\begin{pmatrix}x \\ y\end{pmatrix} = \begin{pmatrix}3\\4\end{pmatrix} \\
&係数の行列式:\ 1\times{4} - 2\times{4} = 0 \quad \therefore この方程式は解けない
\end{align}
$$

$$
\begin{align}
&方程式の上式の2倍から下式を引く:\ 0x + 0y = 2 \\
&\therefore これを満たす x, y は存在しない
\end{align}
$$

また、解が無限に存在する場合の方程式は以下のようなものである

$$
\left\{
\begin{align}
& x + 2y = 2 \\
& 2x + 4y = 4
\end{align}
\right.
$$

$$
\begin{align}
&行列:\ \begin{pmatrix}1&2\\2&4\end{pmatrix}\begin{pmatrix}x \\ y\end{pmatrix} = \begin{pmatrix}2\\4\end{pmatrix} \\
&係数の行列式:\ 1\times{4} - 2\times{4} = 0 \quad \therefore この方程式は解けない
\end{align}
$$

$$
\begin{align}
&方程式の上式の2倍から下式を引く:\ 0x + 0y = 0 \rightarrow 上式と下式は一致する \\
&\therefore これを満たす x, y は無限に存在する
\end{align}
$$

### 逆行列と線形独立性
2次正方行列では、1行目と2行目に対応するベクトルが平行の時に逆行列を持たない、という法則があった

3次以上の場合まで一般化して考えると、逆行列を持たない場合とは「行列の行をベクトルと見たときにそれらが **線形従属** であるとき」と言える

- **線形従属**:
    - ベクトルの集合の少なくともどれか一つのベクトルを他のベクトルの線形結合で表すことが可能な状態
        - 言い換えると、各ベクトルをスカラー倍して和をとったときに、$\boldsymbol{0}$ になる組み合わせが存在する状態
            - ただし、すべてのスカラーが 0 の場合を除く（すべてのベクトルを 0 倍すれば必ず $\boldsymbol{0}$ になるため）
    - 具体例: $\begin{pmatrix}1&1&2\\2&-1&1\\4&1&5\end{pmatrix}$
        - 1行目: $\boldsymbol{c_1} = (1, 1, 2)$
        - 2行目: $\boldsymbol{c_2} = (2, -1, 1)$
        - 3行目: $\boldsymbol{c_3} = (4, 1, 5)$
        - 線形従属: $k_1\boldsymbol{c_1} + k_2\boldsymbol{c_2} + k_3\boldsymbol{c_3} = 0$ になる $k_1, k_2, k_3$ の組み合わせが存在する（ただし $k_1, k_2, k_3$ の少なくとも1つは 0 でないこと）
            - 今回の場合 $2\boldsymbol{c_1} + \boldsymbol{c_2} + (-1)\boldsymbol{c_3} = 0$ が成り立つため線形従属であると言える
- **線形独立**:
    - ベクトルの集合が線形従属でない状態
        - 言い換えると、各ベクトルをスカラー倍して和をとったときに、$\boldsymbol{0}$ になる組み合わせが存在しない状態
            - ただし、すべてのスカラーが 0 の場合を除く（すべてのベクトルを 0 倍すれば必ず $\boldsymbol{0}$ になるため）

2次正方行列の逆行列は、公式から簡単に求めることが可能だったが、ここで一般の正方行列の逆行列の求め方を考えてみる

準備として、行列の **行基本操作** を定義する

- **行基本操作**:
    1. ある行に定数を掛ける
    2. ある行に定数を掛けたものを他のある行に足す
    3. ある行とある行を交換する

続いて、次の具体例をもとに逆行列を求める

$$
\boldsymbol{A} = \begin{pmatrix}3&1&1\\1&2&1\\0&-1&1\end{pmatrix}
$$

この行列の右側に同じサイズの単位行列を連結し、次のような行列を考える

$$
\begin{pmatrix}\boldsymbol{A} & \boldsymbol{I}\end{pmatrix} = \left(
\begin{array}{ccc|ccc}
3&1&1 & 1&& \\
1&2&1 & &1& \\
0&-1&1 & &&1
\end{array}
\right)
$$

この行列に対して行基本操作を繰り返し、左半分が単位行列になったときに右半分に現れるのが逆行列である

$$
\begin{align}
\left(
\begin{array}{ccc|ccc}
3&1&1 & 1&& \\
1&2&1 & &1& \\
0&-1&1 & &&1
\end{array}
\right) &\rightarrow
\left(
\begin{array}{ccc|ccc}
0&-5&-2 & 1&-3&0 \\
1&2&1 & 0&1&0 \\
0&-1&1 & 0&0&1
\end{array}
\right) \quad（①2行目の-3倍を1行目に加える）\\
&\rightarrow
\left(
\begin{array}{ccc|ccc}
1&2&1 & 0&1&0 \\
0&-5&-2 & 1&-3&0 \\
0&-1&1 & 0&0&1
\end{array}
\right) \quad（②1行目と2行目を交換）\\
&\rightarrow
\left(
\begin{array}{ccc|ccc}
1&0&3 & 0&1&2 \\
0&0&-7 & 1&-3&-5 \\
0&-1&1 & 0&0&1
\end{array}
\right) \quad（③1行目に3行目の2倍を加え、2行目に3行目の-5倍を加える）\\
&\rightarrow
\left(
\begin{array}{ccc|ccc}
1&0&3 & 0&1&2 \\
0&-1&1 & 0&0&1 \\
0&0&-7 & 1&-3&-5
\end{array}
\right) \quad（④2行目と3行目を交換）\\
&\rightarrow
\left(
\begin{array}{ccc|ccc}
1&0&3 & 0&1&2 \\
0&1&-1 & 0&0&-1 \\
0&0&-7 & 1&-3&-5
\end{array}
\right) \quad（⑤2行目を-1倍）\\
&\rightarrow
\left(
\begin{array}{ccc|ccc}
1&0&0 & \frac{3}{7}&-\frac{2}{7}&-\frac{1}{7} \\
0&1&0 & -\frac{1}{7}&\frac{3}{7}&-\frac{2}{7} \\
0&0&-7 & 1&-3&-5
\end{array}
\right) \quad（⑥1行目に3行目の\frac{3}{7}倍を加え、2行目に3行目の-\frac{1}{7}を加える）\\
&\rightarrow
\left(
\begin{array}{ccc|ccc}
1&0&0 & \frac{3}{7}&-\frac{2}{7}&-\frac{1}{7} \\
0&1&0 & -\frac{1}{7}&\frac{3}{7}&-\frac{2}{7} \\
0&0&1 & -\frac{1}{7}&\frac{3}{7}&\frac{5}{7}
\end{array}
\right) \quad（⑦3行目を-\frac{1}{7}倍）\\
\end{align}
$$

以上より、上記行列の逆行列は $\begin{pmatrix}\frac{3}{7}&-\frac{2}{7}&-\frac{1}{7} \\ \frac{1}{7}&\frac{3}{7}&-\frac{2}{7} \\ -\frac{1}{7}&\frac{3}{7}&\frac{5}{7}\end{pmatrix}$ となる

実際、元の行列と上記逆行列を掛けてみると単位行列になることが確認できる

In [4]:
# 行列×逆行列（有理数で計算）
[3 1 1; 1 2 1; 0 -1 1] * [3//7 -2//7 -1//7; -1//7 3//7 -2//7; -1//7 3//7 5//7]

3×3 Matrix{Rational{Int64}}:
 1//1  0//1  0//1
 0//1  1//1  0//1
 0//1  0//1  1//1

In [5]:
# 行列×逆行列（有理数で計算したものを整数に戻す）
Int.([3 1 1; 1 2 1; 0 -1 1] * [3//7 -2//7 -1//7; -1//7 3//7 -2//7; -1//7 3//7 5//7])

3×3 Matrix{Int64}:
 1  0  0
 0  1  0
 0  0  1

上記のような操作を以下の非正則行列 $\boldsymbol{B}$ について行ってみる

$$
\begin{align}
\boldsymbol{B} &= \begin{pmatrix}1&1&&2\\1&-1&1\\3&-1&4\end{pmatrix} \\
\\
\begin{pmatrix}\boldsymbol{B} & \boldsymbol{I}\end{pmatrix} &= \begin{pmatrix}1&1&2&1&&\\1&-1&1&&1&\\3&-1&4&&&1\end{pmatrix}\\
&\rightarrow \begin{pmatrix}1&1&2&1&&\\0&-2&-1&-1&1&\\0&-4&-2&-3&&1\end{pmatrix} \quad (①2行目 += -1\times{1行目},\ 3行目 += -3\times{1行目}) \\
&\rightarrow \begin{pmatrix}1&1&2&1&&\\0&1&\frac{1}{2}&\frac{1}{2}&-\frac{1}{2}&\\0&-4&-2&-3&&1\end{pmatrix} \quad (②2行目 = -\frac{1}{2}\times{2行目}) \\
&\rightarrow \begin{pmatrix}1&0&\frac{5}{2}&\frac{1}{2}&\frac{1}{2}&\\0&1&\frac{1}{2}&\frac{1}{2}&-\frac{1}{2}&\\0&0&0&-1&-2&1\end{pmatrix} \quad (③1行目 += -1\times{2行目},\ 3行目 += 4\times{2行目})
\end{align}
$$

上記の通り、3行目の左半分が $\boldsymbol{0}$ となってしまい、これ以上計算できない

このことは元の行列 $\boldsymbol{B}$ が逆行列を持たないことに対応している

ここで、行基本操作の結果の左半分のみに注目すると、上の2行が $\boldsymbol{0}^T$ に一致せず、3行目が $\boldsymbol{0}^T$ に一致している

このように行基本操作を行った結果、$\boldsymbol{0}^T$ に**ならない**行の数を、その行列の **ランク** と呼ぶ

上記行列 $\boldsymbol{B}$ の場合、ランクは 2 であり、$\mathrm{rank}\boldsymbol{B}=2$ と表す

また、正則行列 $\boldsymbol{A}$ の場合は $\mathrm{rank}\boldsymbol{A}=3$ である

一般に **$n$次正方行列がランク$n$であること** と、その行列が正則であることは必要十分の関係となる

ランクの概念は正方行列に限らず、任意の $m\times{n}$ 行列に対しても存在し、ランクは最大で $\min(m, n)$（$m$ と $n$ のうち小さい方の次元数）を超えないことが知られている

特に $\mathrm{rank}\boldsymbol{A} = \min(m, n)$ である時、行列 $\boldsymbol{A}$ は **フルランク** であると呼ばれる

つまり、行列が正則である条件は、その行列がフルランクであることである

#### ランクの求め方
逆行列を求める必要がなく、行列のランクのみを求めたい場合（行列が正則かどうかを調べたい場合）、以下の簡易的な手順で求めることが出来る

1. $m\times{n}$ 行列 $\boldsymbol{A}$ のランクを求める
2. 任意変数 $i$ を $1～m$ まで増やすながら以下の計算を繰り返す
    - $i$ 行目以降で 0 でない成分が出現する行を選択する（もしすべて 0 であれば終了する）
    - 選択した行の最も左の 0 でない列を $k$ 列目として、$i$ 行目以降で選択した行**以外**の $k$ 列目がすべて 0 となるように行基本変形を行う
3. 終了時 $\boldsymbol{0}^T$ に一致しない行の数が $\boldsymbol{A}$ のランクとなる

上記手順で前述の非正則行列 $\boldsymbol{B}$ のランクを求めてみると、

$$
\begin{align}
\boldsymbol{B} &= \begin{pmatrix}1&1&2\\1&-1&1\\3&-1&4\end{pmatrix} \\
&\rightarrow \begin{pmatrix}1&1&2\\0&-2&-1\\0&-4&-2\end{pmatrix} \quad (①2行目+=-1\times{1行目},\ 3行目+=-3\times{1行目}) \\
&\rightarrow \begin{pmatrix}1&1&2\\0&-2&-1\\0&0&0\end{pmatrix} \quad (②3行目+=3\times{2行目})
\end{align}
$$

より、$\mathrm{rank}\boldsymbol{B} = 2$ であることが分かる

### 前進消去と後退代入
前述のように、行基本操作（行基本変形）を用いてある行列を単位行列に変形することで、その行列の逆行列を求めることが出来る

逆行列を求めることができれば、自動的に連立1次方程式を解くことも可能であり、このようなアルゴリズムを **ガウスの消去法** もしくは **掃き出し法** と呼ぶ

ガウスの消去法は **前進消去** と **後退代入** という2つのステップから構成されている

- **前進消去**:
    - **拡大係数行列** に対して行基本操作（行基本変形）を行い、係数行列の対角成分を 1 に、下三角を 0 に変形し、**階段行列** を作ること
    - ![gauss_matrix.drawio.png](./img/gauss_matrix.drawio.png)
- **後退代入**:
    - 連立1次方程式の求解部分のこと
    - 前進消去により求められた階段行列において、最下段の自明な解からドミノ倒し的に解を求めていく
    - ![gauss_backward_base.drawio.png](./img/gauss_backward_base.drawio.png)

ガウスの消去法は機械的に連立1次方程式を解くことが出来るため、コンピュータシミュレーションの分野では基本の手法となっている

#### 前進消去の実装
前進消去は以下のアルゴリズムで処理することが出来る

1. 1行目1列目（$a_11$）を **ピボット** と呼ばれる成分として選択する
2. ピボット成分のある行をピボット値で割り、ピボット値が 1 になるように変形する
3. 2行目以降について、ピボット成分のある列（$a_11$ がピボットの場合は 1 列目）が 0 になるように、ピボット成分のある行（$a_11$ がピボットの場合は 1 行目）を定数倍して加算する
4. ピボット成分を +1 行, +1 列ずらして新たなピボットとして選択する
5. 新しいピボット成分に対して 2～4 の操作を繰り返し、最後の行まで処理する

![gauss_forward.drawio.png](./img/gauss_forward.drawio.png)

#### 後退代入の実装
階段行列の最下段は係数行列の左側が全て0、右端が1になっている

その更に右隣は定数項であるため、既に解が得られている段となる（自明の解）

最下段の解がわかれば、その1つ上の段の未知数も計算可能になるため、以下の図のようにドミノ倒し的に解を求めることができる

![gauss_backward.drawio.png](./img/gauss_backward.drawio.png)

In [6]:
"""
ガウスの消去法

@params
- A::Matrix{T} 係数行列
- b::Vector{T} 定数ベクトル

@keys
- debug::Boolean デバッグ出力するかどうか

@returns
- x::Vector{T} 解ベクトル
"""
gauss_eliminate = (A, b; debug = false) -> begin
    # 拡大係数行列: 係数行列と定数ベクトルを横に結合
    mat = Rational.(hcat(A, b)) # 有理数計算できるように Matrix{Complex} 型とする
    n = size(mat)[1] # 拡大係数行列の行数
    
    # 前進消去
    for i = 1:n # 1行目からn行目までループ処理
        pivot = mat[i, i] # a_ii: ピボットとして選択
        mat[i, :] = mat[i, :] // pivot # i行目: ピボット値で割る（ピボット値を 1 にする）
        
        # 1行目の定数倍を i+1 行目から n 行目まで加算
        for j = i+1 : n
            mat[j, :] = mat[j, :] - mat[j, i] .* mat[i, :] # i列目の値が 0 になるように i行目を定数倍して加算（減産）
        end
    end
    
    # 前進消去後の拡大係数行列を確認
    if debug
        display(mat)
    end
    
    # 後退代入
    x = zeros(Float64, n) # n次元 解ベクトル
    A, b = mat[:, 1:end-1], mat[:, end] # 拡大係数行列を係数行列と定数ベクトルに再分離
    for i = n:-1:1 # 最終行から解を求めていく
        x[i] = b[i] # 自明の解
        for j = 1:i
            b[j] = b[j] - A[j, i] * x[i] # 解が決まった列分、定数ベクトルの値を更新
        end
    end
    
    return x
end

gauss_eliminate

In [7]:
# 例で挙げていた連立1次方程式を実際に解いてみる
A = [2 1 3 4; 3 2 5 2; 3 4 1 -1; -1 -3 1 3]
b = [2; 12; 4; -1]

gauss_eliminate(A, b; debug=true)

4×5 Matrix{Rational{Int64}}:
 1//1  1//2  3//2    2//1   1//1
 0//1  1//1  1//1   -8//1  18//1
 0//1  0//1  1//1  -13//6  22//3
 0//1  0//1  0//1    1//1  -2//1

4-element Vector{Float64}:
  1.0
 -1.0
  3.0
 -2.0